# Generated by Django 3.2.7 on 2021-12-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='updated_user',
        ),
    ]
