# Generated by Django 3.2.7 on 2021-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_event_eventcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
