# Generated by Django 3.2.7 on 2021-12-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211204_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='update_time',
        ),
    ]
