# Generated by Django 3.2.7 on 2021-12-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_volunteer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
