# Generated by Django 3.2.7 on 2021-12-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_delete_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='volunteer_images/')),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
