# Generated by Django 3.2.7 on 2021-12-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
